# Generated by Django 4.2.4 on 2023-08-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated', '-created', 'price']},
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilo Gram'), ('t', 'Ton'), ('m', 'Meter')], max_length=150),
        ),
        migrations.CreateModel(
            name='VariantProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('products', models.ManyToManyField(to='products.product')),
            ],
            options={
                'db_table': 'products_variants',
            },
        ),
    ]
