# Generated by Django 4.2.4 on 2023-08-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_variantproduct_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariantProduct',
            new_name='Variant',
        ),
        migrations.AlterModelTable(
            name='variant',
            table='variants',
        ),
    ]
